# Generated by Django 3.1.2 on 2021-11-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211102_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='relation',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной'),
        ),
    ]
