# Generated by Django 3.1.2 on 2021-11-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211120_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='theme',
            new_name='topic',
        ),
    ]
